sudo: false
language: c
matrix:
  include:
  - os: osx
    compiler: gcc
    env: PATH=./racket/bin:$PATH
  - os: osx
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places --disable-futures --disable-extflonum"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places
      --disable-futures --disable-extflonum"
before_script:
- git config --global user.email "travis-test@racket-lang.org"
- git config --global user.name "Travis Tester"
script:
- make CPUS="2" PKGS="racket-test db-test unstable-flonum-lib net-test" CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"
- racket -f pkgs/racket-test-core/tests/racket/file.rktl 
notifications:
  irc: chat.freenode.net#racket-dev
  email:
    recipients:
    - samth@racket-lang.org
    - robby@racket-lang.org
    - mflatt@racket-lang.org
    on_success: change
  slack:
    secure: A19kphrabQHO8TU6qZcBaLQxdSNpm1ypEtbQsh8Ucg6HYPP7y1q7O7JZEndoMRHE9CNKZ9oXQzqR8H1IFVTlnjFFIJfkZzZ1YSNk4abSomhpWCq9daKMfwlcuTtY6PeI1nDVpka4/hiJGn9qzmaKYXle9Sl4CX2VEYp8o8PgMEs=
    rooms:
      secure: FsKzp4ItmOqd/YxqgsElgfjGW2/TU03p2p3ss+PQl/pKDQNnR/2b4pWCQ7GuqYibkmtiH1jYwrnuaLN4Cc+JyN7Z+zUtO4VSORsh3zt/gTsfgphMpCP6cB4sTqUh6AWsZOgzikj+fh7ORHEXVswQwlRHErTgZVEdEkWHBh4UWzc=
