name: Solo Chez Build

on:
  push:
    paths:
      - "racket/src/ChezScheme/**"
      - ".github/scripts/**"
      - ".github/workflows/chez-build.yml"
      - "Makefile"
  pull_request:
    paths:
      - "racket/src/ChezScheme/**"
      - ".github/scripts/**"
      - ".github/workflows/chez-build.yml"
      - "Makefile"
      
permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        mach: ['i3le', 'ti3le', 'a6le', 'ta6le'] 

    env:
      MACH: ${{ matrix.mach }}

    steps:
      - name: Download base dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git gcc
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Download pb boot files
        run: make fetch-pb
      - name: Proceed with TARGET_MACHINE == ${{ matrix.mach }}
        run: echo $TARGET_MACHINE
      - name: Install libs for 32-bit
        if: matrix.mach == 'i3le' || matrix.mach == 'ti3le'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib lib32ncurses-dev libssl-dev:i386
      - name: Install libs for 64-bit
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libssl-dev libx11-dev
      - name: Build Chez with PB boot files
        working-directory: racket/src/ChezScheme
        run: |
          ./configure --pb
          make -j$(($(nproc) + 1)) -l$(nproc) ${{ matrix.mach }}.bootquick
      - name: Build Chez with native boot files
        working-directory: racket/src/ChezScheme
        run: |
          ./configure -m=${{ matrix.mach }}
          make -j$(($(nproc) + 1)) -l$(nproc)
      - name: Test Chez
        working-directory: racket/src/ChezScheme
        run: ../../../.github/scripts/test.sh
