name: Test with ASan

on: [push]

permissions:
  contents: read

jobs:

  racketcs-asan:
    runs-on: ubuntu-22.04
    container: racket/racket-ci:latest

    env:
      ASAN_OPTIONS: 'halt_on_error=0,log_path=racket-asan'
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
    - name: Create logs directory
      run: mkdir $PWD/logs
    - name: Build
      run: |
        export cpus=$(grep -c ^processor /proc/cpuinfo)
        make CPUS="${cpus}" PKGS="racket-test db-test unstable-flonum-lib net-test" CONFIGURE_ARGS_qq='--enable-asan' cs-in-place 2>&1 | tee logs/build.log
    - name: Add new racket to PATH
      run: |
        echo "${GITHUB_WORKSPACE}/racket/bin" >> $GITHUB_PATH
        find /__w/racket/racket/racket/bin -type f
    - name: Racket version
      run: |
        which racket
        racket --version
    - name: Run tests/racket/test
      continue-on-error: true
      run: raco test -l tests/racket/test 
    - name: Run tests/racket/contract/all
      continue-on-error: true
      run: racket -l tests/racket/contract/all
    - name: Run tests/json/json
      continue-on-error: true
      run: raco test -l tests/json/json
    - name: Run tests/file/main
      continue-on-error: true
      run: raco test -l tests/file/main
    - name: Run tests/net/head
      continue-on-error: true
      run: raco test -l tests/net/head 
    - name: Run tests/net/uri-codec
      continue-on-error: true
      run: raco test -l tests/net/uri-codec
    - name: Run tests/net/url
      continue-on-error: true
      run: raco test -l tests/net/url
    - name: Run tests/net/url-port
      continue-on-error: true
      run: raco test -l tests/net/url-port
    - name: Run tests/net/encoders
      continue-on-error: true
      run: raco test -l tests/net/encoders
    - name: Run tests/openssl/basic
      continue-on-error: true
      run: raco test -l tests/openssl/basic
    - name: Run tests/openssl/https
      continue-on-error: true
      run: raco test -l tests/openssl/https
    - name: Run tests/match/main
      continue-on-error: true
      run: raco test -l tests/match/main
    - name: Run tests/zo-path
      continue-on-error: true
      run: raco test -l tests/zo-path
    - name: Run tests/xml
      continue-on-error: true
      run: raco test -c tests/xml 
    - name: Run tests/future
      continue-on-error: true
      run: raco test --timeout 300 -c tests/future
    - name: Run tests/stxparse
      continue-on-error: true
      run: raco test -c tests/stxparse
    - name: Run db tests
      continue-on-error: true
      run: raco test -l tests/db/all-tests
    - uses: actions/upload-artifact@v3
      with:
        name: asan-errors-cs_git${{ github.sha }}
        path: ./racket-asan.*
