name: CI Linux ARM

on: [push]

jobs:

# Build jobs
# These jobs build each Racket component separately and tests on the component start as soon as each
# component finishes building.

  build-racketcgc:
    strategy:
      fail-fast: false
      matrix:
        cify: [cify, nocify]
        arch: [ARM64]
    
    runs-on: [self-hosted, Linux, '${{ matrix.arch }}']
    container:
      image: racket/racket-ci:latest
    
    steps:
    - name: Clean racket pkg folder
      run: rm -rf $HOME/.racket
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Setup jit if ARM
      if: matrix.arch == 'ARM'
      run: echo "::set-env name=JIT_OPTION::--enable-jit --enable-futures"
    - name: Setup jit if ARM64
      if: matrix.arch == 'ARM64'
      run: echo "::set-env name=JIT_OPTION::--disable-jit --disable-futures"
    - name: Setup cify if enabled
      if: matrix.cify == 'cify'
      run: echo "::set-env name=CIFY_OPTION::--enable-cify"
    - name: Setup cify if disabled
      if: matrix.cify == 'nocify'
      run: echo "::set-env name=CIFY_OPTION::--disable-cify"
    - name: Configuring Racket CGC
      working-directory: ./racket/src
      run: >
        ./configure
        --prefix=/usr/local/racketcgc
        --enable-werror
        --enable-cgcdefault
        --enable-foreign
        --enable-places
        --enable-float
        $JIT_OPTION
        $CIFY_OPTION
        --enable-pthread
        --disable-docs
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(nproc)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j  $((cpus+1)) install
    - name: Tarballing
      working-directory: /usr/local
      run: tar -cvjf /tmp/racketcgc-debian10-${{ matrix.cify }}-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2 racketcgc
    - uses: actions/upload-artifact@v2
      with:
        name: racketcgc-debian10-${{ matrix.cify }}-${{ matrix.arch }}_git${{ github.sha }}
        path: /tmp/racketcgc-debian10-${{ matrix.cify }}-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2

  build-racket3m:
    container:
      image: racket/racket-ci:latest
                
    needs: build-racketcgc
      
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM64]
        cify: [cify, nocify]
        cc: [gcc, clang]
        ep: [ep, noep]

    runs-on: [self-hosted, Linux, '${{ matrix.arch }}']

    steps:
    - name: Clean racket pkg folder
      run: rm -rf $HOME/.racket
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Setup cify if enabled
      if: matrix.cify == 'cify'
      run: echo "::set-env name=CIFY_OPTION::--enable-cify"
    - name: Setup cify if disabled
      if: matrix.cify == 'nocify'
      run: echo "::set-env name=CIFY_OPTION::--disable-cify"
    - name: Setup ep if enabled
      if: matrix.ep == 'ep'
      run: echo "::set-env name=EP_OPTIONS::--enable-extflonums --enable-places"
    - name: Setup efp if disabled
      if: matrix.efp == 'noep'
      run: echo "::set-env name=EP_OPTIONS::--disable-extflonums --disable-places"
    - uses: actions/download-artifact@v2
      with:
        name: racketcgc-debian10-nocify-${{ matrix.arch }}_git${{ github.sha }}
        path: /tmp
    - name: Untar
      working-directory: /usr/local
      run: tar -xvjf /tmp/racketcgc-debian10-nocify-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2
    - name: Configuring Racket 3m
      working-directory: ./racket/src
      env:
        CC: ${{ matrix.cc }}
      run: >
        ./configure
        --prefix=/usr/local/racket3m
        --enable-bcdefault
        --enable-bconly
        --enable-werror
        --enable-racket=/usr/local/racketcgc/bin/racket
        --enable-foreign
        --enable-float
        --disable-docs
        $CIFY_OPTION
        $EP_OPTIONS
        --enable-pthread
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(nproc)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j $((cpus+1)) install
    # We build on Linux with clang and gcc and on MacOS with clang only.
    # However, it makes little sense to test both builds on Linux so we tarball the
    # gcc build only. Therefore this condition ensure we only perform the tarball
    # and artifact upload on MacOS or (on Linux) if we are building with gcc.
    - name: Tarballing
      working-directory: /usr/local
      run: tar -cvjf /tmp/racket3m-debian10-${{ matrix.cify }}-${{ matrix.ep }}-${{ matrix.arch }}_git${{ github.sha}}.tar.bz2 racket3m
    - uses: actions/upload-artifact@v2
      if: matrix.cc == 'gcc'
      with:
        name: racket3m-debian10-${{ matrix.cify }}-${{ matrix.ep }}-${{ matrix.arch }}_git${{ github.sha }}
        path: /tmp/racket3m-debian10-${{ matrix.cify }}-${{ matrix.ep }}-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2

  build-racketcs:
    container:
      image: racket/racket-ci:latest

    needs: build-racketcgc
    
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM64]
        cc: [gcc, clang]

    runs-on: [self-hosted, Linux, '${{ matrix.arch }}']

    steps:
    - name: Clean racket pkg folder
      run: rm -rf $HOME/.racket
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - uses: actions/download-artifact@v2
      with:
        name: racketcgc-debian10-nocify-${{ matrix.arch }}_git${{ github.sha }}
        path: /tmp
    - name: Untar
      working-directory: /usr/local
      run: tar -xvjf /tmp/racketcgc-debian10-nocify-${{ matrix.arch }}_git${{ github.sha}}.tar.bz2
    - name: Checking out ChezScheme
      working-directory: ./racket/src
      run: git clone --depth=1 --recurse-submodules -j3 https://github.com/racket/ChezScheme
    - name: Configuring Racket CS
      working-directory: ./racket/src
      env:
        CC: ${{ matrix.cc }}
      run: >
        ./configure
        --prefix=/usr/local/racketcs
        $RACKET_EXTRA_CONFIGURE_ARGS
        --enable-racket=/usr/local/racketcgc/bin/racket
        --enable-compress
        --disable-docs
        --enable-pthread
        --enable-csdefault
        --enable-csonly
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(nproc)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j  $((cpus+1)) install
    - name: Tarballing
      working-directory: /usr/local
      run: tar -cvjf /tmp/racketcs-debian10-${{ matrix.arch }}_git${{ github.sha}}.tar.bz2 racketcs
    - uses: actions/upload-artifact@v2
      with:
        name: racketcs-debian10-${{ matrix.arch }}_git${{ github.sha }}
        path: /tmp/racketcs-debian10-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2

  # Tests
  # Unfortunately Actions does not support atm yaml anchors
  # otherwise all the following jobs could be simplified
  # Note: the reason we cannot transform this into a matrix
  # build is because we cannot use variables in the needs keyword.
  test-cgc:
    container:
      image: racket/racket-ci:latest
      options: --init

    needs: build-racketcgc

    strategy:
      fail-fast: false
      matrix:
        arch: [ARM64]
        cify: [cify, nocify]

    runs-on: [self-hosted, Linux, '${{ matrix.arch }}']

    steps:
      - name: Clean racket pkg folder
        run: rm -rf $HOME/.racket
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: racketcgc-debian10-${{ matrix.cify }}-${{ matrix.arch }}_git${{ github.sha }}
          path: /tmp
      - name: Untar
        working-directory: /usr/local
        run: tar -xvjf /tmp/racketcgc-debian10-${{ matrix.cify }}-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        run: echo "::set-env name=PATH::/usr/local/racketcgc/bin:$PATH"
      - name: Check for Racket
        run: racket --version
      - name: Install catalog
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Run tests/racket/test
        run: raco test -l tests/racket/test
      - name: Run tests/racket/contract/all
        run: racket -l tests/racket/contract/all
      - name: Run tests/json/json
        run: raco test -l tests/json/json
      - name: Run tests/file/main
        run: raco test -l tests/file/main
      - name: Run tests/net/head
        run: raco test -l tests/net/head
      - name: Run tests/net/uri-codec
        run: raco test -l tests/net/uri-codec
      - name: Run tests/net/url
        run: raco test -l tests/net/url
      - name: Run tests/net/url-port
        run: raco test -l tests/net/url-port
      - name: Run tests/net/encoders
        run: raco test -l tests/net/encoders
      - name: Run tests/openssl/basic
        run: raco test -l tests/openssl/basic
      - name: Run tests/openssl/https
        run: raco test -l tests/openssl/https
      - name: Run tests/match/main
        run: raco test -l tests/match/main
      - name: Run tests/zo-path
        run: raco test -l tests/zo-path
      - name: Run tests/xml
        run: raco test -c tests/xml
      - name: Run tests/future
        run: raco test -c tests/future
      - name: Run tests/stxparse
        run: raco test -c tests/stxparse
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Run db tests
        run: raco test -l tests/db/all-tests
      - name: Run syntax tests
        run: raco test -c tests/syntax

  test-3m:
    container:
      image: racket/racket-ci:latest
      options: --init

    needs: build-racket3m

    strategy:
      fail-fast: false
      matrix:
        arch: [ARM64]
        cify: [cify, nocify]
        ep: [ep, noep]

    runs-on: [self-hosted, Linux, '${{ matrix.arch }}']

    steps:
      - name: Clean racket pkg folder
        run: rm -rf $HOME/.racket
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: racket3m-debian10-${{ matrix.cify }}-${{ matrix.ep }}-${{ matrix.arch }}_git${{ github.sha }}
          path: /tmp
      - name: Untar
        working-directory: /usr/local
        run: tar -xvjf /tmp/racket3m-debian10-${{ matrix.cify }}-${{ matrix.ep }}-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        run: echo "::set-env name=PATH::/usr/local/racket3m/bin:$PATH"
      - name: Check for Racket
        run: racket --version
      - name: Install catalog and required packages
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Run tests/racket/test
        run: raco test -l tests/racket/test
      - name: Run tests/racket/contract/all
        run: racket -l tests/racket/contract/all
      - name: Run tests/json/json
        run: raco test -l tests/json/json
      - name: Run tests/file/main
        run: raco test -l tests/file/main
      - name: Run tests/net/head
        run: raco test -l tests/net/head
      - name: Run tests/net/uri-codec
        run: raco test -l tests/net/uri-codec
      - name: Run tests/net/url
        run: raco test -l tests/net/url
      - name: Run tests/net/url-port
        run: raco test -l tests/net/url-port
      - name: Run tests/net/encoders
        run: raco test -l tests/net/encoders
      - name: Run tests/openssl/basic
        run: raco test -l tests/openssl/basic
      - name: Run tests/openssl/https
        run: raco test -l tests/openssl/https
      - name: Run tests/match/main
        run: raco test -l tests/match/main
      - name: Run tests/zo-path
        run: raco test -l tests/zo-path
      - name: Run tests/xml
        run: raco test -c tests/xml
      - name: Run tests/future
        run: raco test -c tests/future
      - name: Run tests/stxparse
        run: raco test -c tests/stxparse
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Run db tests
        run: raco test -l tests/db/all-tests

  test-cs:
    container:
      image: racket/racket-ci:latest
      options: --init

    strategy:
      matrix:
        arch: [ARM64]
      
    needs: build-racketcs

    runs-on: [self-hosted, Linux, '${{ matrix.arch }}']
        
    steps:
      - name: Clean racket pkg folder
        run: rm -rf $HOME/.racket
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: racketcs-debian10-${{ matrix.arch }}_git${{ github.sha }}
          path: /tmp
      - name: Untar
        working-directory: /usr/local
        run: tar -xvjf /tmp/racketcs-debian10-${{ matrix.arch }}_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        run: echo "::set-env name=PATH::/usr/local/racketcs/bin:$PATH"
      - name: Check for Racket
        run: racket --version
      - name: Install catalog and required packages
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Run tests/racket/test
        run: raco test -l tests/racket/test
      - name: Run tests/racket/contract/all
        run: racket -l tests/racket/contract/all
      - name: Run tests/json/json
        run: raco test -l tests/json/json
      - name: Run tests/file/main
        run: raco test -l tests/file/main
      - name: Run tests/net/head
        run: raco test -l tests/net/head
      - name: Run tests/net/uri-codec
        run: raco test -l tests/net/uri-codec
      - name: Run tests/net/url
        run: raco test -l tests/net/url
      - name: Run tests/net/url-port
        run: raco test -l tests/net/url-port
      - name: Run tests/net/encoders
        run: raco test -l tests/net/encoders
      - name: Run tests/openssl/basic
        run: raco test -l tests/openssl/basic
      - name: Run tests/openssl/https
        run: raco test -l tests/openssl/https
      - name: Run tests/match/main
        run: raco test -l tests/match/main
      - name: Run tests/zo-path
        run: raco test -l tests/zo-path
      - name: Run tests/xml
        run: raco test -c tests/xml
      - name: Run tests/future
        run: raco test -c tests/future
      - name: Run tests/stxparse
        run: raco test -c tests/stxparse
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Run db tests
        run: raco test -l tests/db/all-tests
