name: CI Linux x86

on:
  push:
    branches:
      - master

jobs:

# Build jobs
# These jobs build each Racket component separately and tests on the component start as soon as each
# component finishes building.

  build-racketcgc:
    runs-on: ubuntu-22.04
    container:
      image: racket/racket-ci:latest

    strategy:
      fail-fast: false
      matrix:
        cify: [nocify]

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 100
    - name: Setup cify if enabled
      if: matrix.cify == 'cify'
      run: echo "CIFY_OPTION=--enable-cify" >> $GITHUB_ENV
    - name: Setup cify if disabled
      if: matrix.cify == 'nocify'
      run: echo "CIFY_OPTION=--disable-cify" >> $GITHUB_ENV
    - name: Configuring Racket CGC
      working-directory: ./racket/src
      run: >
        ./configure
        --prefix=/usr/local/racketcgc
        --enable-werror
        --enable-cgcdefault
        --enable-jit
        --enable-foreign
        --enable-places
        --enable-futures
        --enable-float
        $CIFY_OPTION
        --enable-pthread
        --disable-docs
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(nproc)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j  $((cpus+1)) install
    - name: Tarballing
      working-directory: /usr/local
      run: tar -cvjf /tmp/racketcgc-debian10-${{ matrix.cify }}-x64_git${{ github.sha }}.tar.bz2 racketcgc
    - uses: actions/upload-artifact@v6
      with:
        name: racketcgc-debian10-${{ matrix.cify }}-x64_git${{ github.sha }}
        path: /tmp/racketcgc-debian10-${{ matrix.cify }}-x64_git${{ github.sha }}.tar.bz2

  build-racket3m:
    runs-on: ubuntu-22.04
    container:
      image: racket/racket-ci:latest

    needs: build-racketcgc

    strategy:
      fail-fast: false
      matrix:
        cify: [nocify]
        jit: [jit]
        efp: [efp]
        cc: [gcc]
        include:
          - jit: nojit
            cify: cify
            efp: noefp
            cc: gcc
          - jit: jit
            cify: nocify
            efp: efp
            cc: gcc # clang has a problem with future tests timing out

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 100
    - name: Setup cify if enabled
      if: matrix.cify == 'cify'
      run: echo "CIFY_OPTION=--enable-cify" >> $GITHUB_ENV
    - name: Setup cify if disabled
      if: matrix.cify == 'nocify'
      run: echo "CIFY_OPTION=--disable-cify" >> $GITHUB_ENV
    - name: Setup jit if enabled
      if: matrix.jit == 'jit'
      run: echo "JIT_OPTION=--enable-jit" >> $GITHUB_ENV
    - name: Setup jit if disabled
      if: matrix.jit == 'nojit'
      run: echo "JIT_OPTION=--disable-jit" >> $GITHUB_ENV
    - name: Setup efp if enabled
      if: matrix.efp == 'efp'
      run: echo "EFP_OPTIONS=--enable-extflonums --enable-places --enable-futures" >> $GITHUB_ENV
    - name: Setup efp if disabled
      if: matrix.efp == 'noefp'
      run: echo "EFP_OPTIONS=--disable-extflonums --disable-places --disable-futures" >> $GITHUB_ENV
    - uses: actions/download-artifact@v7
      with:
        name: racketcgc-debian10-nocify-x64_git${{ github.sha }}
        path: /tmp
    - name: Untar
      working-directory: /usr/local
      run: tar -xvjf /tmp/racketcgc-debian10-nocify-x64_git${{ github.sha }}.tar.bz2
    - name: Configuring Racket 3m
      working-directory: ./racket/src
      env:
        CC: ${{ matrix.cc }}
      run: >
        ./configure
        --prefix=/usr/local/racket3m
        --enable-werror
        --enable-bcdefault
        --enable-racket=/usr/local/racketcgc/bin/racket
        --enable-foreign
        --enable-float
        --disable-docs
        $CIFY_OPTION
        $JIT_OPTION
        $EFP_OPTIONS
        --enable-pthread
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(nproc)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j $((cpus+1)) install
    # We build on Linux with gcc and on MacOS with clang only.
    - name: Tarballing
      working-directory: /usr/local
      run: tar -cvjf /tmp/racket3m-debian10-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha}}.tar.bz2 racket3m
    - uses: actions/upload-artifact@v6
      with:
        name: racket3m-debian10-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}
        path: /tmp/racket3m-debian10-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}.tar.bz2

  build-racketcs:
    runs-on: ubuntu-22.04
    container:
      image: racket/racket-ci:latest

    needs: build-racketcgc

    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 100
    - uses: actions/download-artifact@v7
      with:
        name: racketcgc-debian10-nocify-x64_git${{ github.sha }}
        path: /tmp
    - name: Untar
      working-directory: /usr/local
      run: tar -xvjf /tmp/racketcgc-debian10-nocify-x64_git${{ github.sha }}.tar.bz2
    - name: Configuring Racket CS
      working-directory: ./racket/src
      env:
        CC: ${{ matrix.cc }}
      run: >
        ./configure
        --prefix=/usr/local/racketcs
        $RACKET_EXTRA_CONFIGURE_ARGS
        --enable-racket=/usr/local/racketcgc/bin/racket
        --enable-compress
        --disable-docs
        --enable-pthread
        --enable-csdefault
        --enable-csonly
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(nproc)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j  $((cpus+1)) install
    - name: Tarballing
      working-directory: /usr/local
      run: tar -cvjf /tmp/racketcs-debian10-x64-${{ matrix.cc }}_git${{ github.sha }}.tar.bz2 racketcs
    - uses: actions/upload-artifact@v6
      with:
        name: racketcs-debian10-x64-${{ matrix.cc }}_git${{ github.sha }}
        path: /tmp/racketcs-debian10-x64-${{ matrix.cc }}_git${{ github.sha }}.tar.bz2

  # Tests
  # Note: the reason we cannot transform this into a matrix build is
  # because we cannot use variables in the needs keyword.
  test-cgc:
    runs-on: ubuntu-22.04
    container:
      image: racket/racket-ci:latest
      options: --init

    needs: build-racketcgc

    strategy:
      fail-fast: false
      matrix:
        cify: [nocify]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: racketcgc-debian10-${{ matrix.cify }}-x64_git${{ github.sha }}
          path: /tmp
      - name: Untar
        working-directory: /usr/local
        run: tar -xvjf /tmp/racketcgc-debian10-${{ matrix.cify }}-x64_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        run: echo "/usr/local/racketcgc/bin" >> $GITHUB_PATH
      - name: Check for Racket
        run: racket --version
      - name: Install catalog
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Test
        run: bash .github/scripts/run-racket-tests.sh

  test-3m:
    runs-on: ubuntu-22.04
    container:
      image: racket/racket-ci:latest
      options: --init

    needs: build-racket3m

    strategy:
      fail-fast: false
      matrix:
        cify: [nocify]
        jit: [jit]
        efp: [efp]
        cc: [gcc]
        include:
          - jit: nojit
            cify: cify
            efp: noefp
            cc: gcc
          - jit: jit
            cify: nocify
            efp: efp
            cc: gcc

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: racket3m-debian10-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}
          path: /tmp
      - name: Untar
        working-directory: /usr/local
        run: tar -xvjf /tmp/racket3m-debian10-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        run: echo "/usr/local/racket3m/bin" >> $GITHUB_PATH
      - name: Check for Racket
        run: racket --version
      - name: Install catalog and required packages
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Test
        run: bash .github/scripts/run-racket-tests.sh

  test-cs:
    runs-on: ubuntu-22.04
    container:
      image: racket/racket-ci:latest
      options: --init

    needs: build-racketcs

    strategy:
      fail-fast: false
      matrix:
        cc: [gcc]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: racketcs-debian10-x64-${{ matrix.cc }}_git${{ github.sha }}
          path: /tmp
      - name: Untar
        working-directory: /usr/local
        run: tar -xvjf /tmp/racketcs-debian10-x64-${{ matrix.cc }}_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        run: echo "/usr/local/racketcs/bin" >> $GITHUB_PATH
      - name: Check for Racket
        run: racket --version
      - name: Install catalog and required packages
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Test
        run: bash .github/scripts/run-racket-tests.sh

  # XXX: Do we still need/want this?
  slack:
    runs-on: ubuntu-latest
    needs: [test-cgc, test-3m, test-cs]

    # this is required, otherwise it gets skipped if any needed jobs fail.
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
    if: always()

    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        if: github.repository == 'racket/racket'
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          author_name: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
