name: CI

on: [push]

jobs:

# Build jobs
# These jobs build each Racket component separately and tests on the component start as soon as each
# component finishes building.

  build-racketcgc:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        cify: [cify, nocify]

    runs-on: ${{ matrix.os }}
    env:
      RACKET_EXTRA_CONFIGURE_ARGS: ""

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 100
    - name: Setup OS specific configure args
      if:  runner.os == 'macOS'
      run: echo "::set-env name=RACKET_EXTRA_CONFIGURE_ARGS::--enable-macprefix $RACKET_EXTRA_CONFIGURE_ARGS"
    - name: Setup cify if enabled
      if: matrix.cify == 'cify'
      run: echo "::set-env name=CIFY_OPTION::--enable-cify"
    - name: Setup cify if disabled
      if: matrix.cify == 'nocify'
      run: echo "::set-env name=CIFY_OPTION::--disable-cify"
    - name: Configuring Racket CGC
      working-directory: ./racket/src
      run: >
        ./configure
        --prefix=${{ runner.temp }}/racketcgc
        --enable-werror
        $RACKET_EXTRA_CONFIGURE_ARGS
        --enable-cgcdefault
        --enable-jit
        --enable-foreign
        --enable-places
        --enable-futures
        --enable-float
        $CIFY_OPTION
        --enable-pthread
        --disable-docs
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(grep -c ^processor /proc/cpuinfo)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j  $((cpus+1)) install
    - name: Tarballing
      working-directory: ${{ runner.temp }}
      run: tar -cvjf racketcgc-${{ matrix.os }}-${{ matrix.cify }}-x64_git${{ github.sha }}.tar.bz2 racketcgc
    - uses: actions/upload-artifact@v1
      with:
        name: racketcgc-${{ matrix.os }}-${{ matrix.cify }}-x64_git${{ github.sha }}
        path: ${{ runner.temp }}/racketcgc-${{ matrix.os }}-${{ matrix.cify }}-x64_git${{ github.sha }}.tar.bz2

  build-racket3m:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        cc: [gcc, clang]
        cify: [cify, nocify]
        jit: [jit, nojit]
        efp: [efp, noefp]
        exclude:
          - os: macos-latest
            cc: gcc
          - jit: nojit
            efp: efp

    runs-on: ${{ matrix.os }}
    needs: build-racketcgc

    env:
      RACKET_EXTRA_CONFIGURE_ARGS: ""

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 100
    - name: Setup OS specific configure args
      if:  runner.os == 'macOS'
      run: echo "::set-env name=RACKET_EXTRA_CONFIGURE_ARGS::--enable-macprefix $RACKET_EXTRA_CONFIGURE_ARGS"
    - name: Setup cify if enabled
      if: matrix.cify == 'cify'
      run: echo "::set-env name=CIFY_OPTION::--enable-cify"
    - name: Setup cify if disabled
      if: matrix.cify == 'nocify'
      run: echo "::set-env name=CIFY_OPTION::--disable-cify"
    - name: Setup jit if enabled
      if: matrix.jit == 'jit'
      run: echo "::set-env name=JIT_OPTION::--enable-jit"
    - name: Setup jit if disabled
      if: matrix.jit == 'nojit'
      run: echo "::set-env name=JIT_OPTION::--disable-jit"
    - name: Setup efp if enabled
      if: matrix.efp == 'efp'
      run: echo "::set-env name=EFP_OPTIONS::--enable-extflonums --enable-places --enable-futures"
    - name: Setup efp if disabled
      if: matrix.efp == 'noefp'
      run: echo "::set-env name=EFP_OPTIONS::--disable-extflonums --disable-places --disable-futures"
    - uses: actions/download-artifact@v1
      with:
        name: racketcgc-${{ matrix.os }}-nocify-x64_git${{ github.sha }}
        path: ${{ runner.temp }}
    - name: Untar
      working-directory: ${{ runner.temp }}
      run: tar -xvjf racketcgc-${{ matrix.os }}-nocify-x64_git${{ github.sha }}.tar.bz2
    - name: Configuring Racket 3m
      working-directory: ./racket/src
      env:
        CC: ${{ matrix.cc }}
      run: >
        ./configure
        --prefix=${{ runner.temp }}/racket3m
        --enable-werror
        $RACKET_EXTRA_CONFIGURE_ARGS
        --enable-racket=${{ runner.temp }}/racketcgc/bin/racket
        --enable-foreign
        --enable-float
        --disable-docs
        $CIFY_OPTION
        $JIT_OPTION
        $EFP_OPTIONS
        --enable-pthread
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(grep -c ^processor /proc/cpuinfo)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j $((cpus+1)) install
    # We build on Linux with clang and gcc and on MacOS with clang only.
    # However, it makes little sense to test both builds on Linux so we tarball the
    # gcc build only. Therefore this condition ensure we only perform the tarball
    # and artifact upload on MacOS or (on Linux) if we are building with gcc.
    - name: Tarballing
      if: matrix.cc == 'gcc' || matrix.os == 'macos-latest'
      working-directory: ${{ runner.temp }}
      run: tar -cvjf racket3m-${{ matrix.os }}-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha}}.tar.bz2 racket3m
    - uses: actions/upload-artifact@v1
      if: matrix.cc == 'gcc' || matrix.os == 'macos-latest'
      with:
        name: racket3m-${{ matrix.os }}-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}
        path: ${{ runner.temp }}/racket3m-${{ matrix.os }}-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}.tar.bz2

  build-racketcs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        cc: [gcc, clang]
        exclude:
          - os: macos-latest
            cc: gcc

    runs-on: ${{ matrix.os }}
    needs: build-racketcgc

    env:
      RACKET_EXTRA_CONFIGURE_ARGS: ""

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 100
    - name: Setup OS specific configure args
      if:  runner.os == 'macOS'
      run: echo "::set-env name=RACKET_EXTRA_CONFIGURE_ARGS::--enable-macprefix $RACKET_EXTRA_CONFIGURE_ARGS"
    - uses: actions/download-artifact@v1
      with:
        name: racketcgc-${{ matrix.os }}-nocify-x64_git${{ github.sha }}
        path: ${{ runner.temp }}
    - name: Untar
      working-directory: ${{ runner.temp }}
      run: tar -xvjf racketcgc-${{ matrix.os }}-nocify-x64_git${{ github.sha}}.tar.bz2
    - name: Install pkg dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y git uuid-dev
    - name: Checking out ChezScheme
      working-directory: ./racket/src
      run: git clone --depth=1 --recurse-submodules -j3 https://github.com/racket/ChezScheme
    - name: Configuring Racket CS
      working-directory: ./racket/src
      env:
        CC: ${{ matrix.cc }}
      run: >
        ./configure
        --prefix=${{ runner.temp }}/racketcs
        $RACKET_EXTRA_CONFIGURE_ARGS
        --enable-racket=${{ runner.temp }}/racketcgc/bin/racket
        --enable-compress
        --disable-docs
        --enable-pthread
        --enable-csdefault
        --enable-csonly
    - name: Building
      working-directory: ./racket/src
      run: |
        export cpus=$(grep -c ^processor /proc/cpuinfo)
        make -l $cpus -j $((cpus+1))
    - name: Installing
      working-directory: ./racket/src
      run: make -j  $((cpus+1)) install
    - name: Tarballing
      if: matrix.cc == 'gcc' || matrix.os == 'macos-latest'
      working-directory: ${{ runner.temp }}
      run: tar -cvjf racketcs-${{ matrix.os }}-x64_git${{ github.sha}}.tar.bz2 racketcs
    - uses: actions/upload-artifact@v1
      if: matrix.cc == 'gcc' || matrix.os == 'macos-latest'
      with:
        name: racketcs-${{ matrix.os }}-x64_git${{ github.sha }}
        path: ${{ runner.temp }}/racketcs-${{ matrix.os }}-x64_git${{ github.sha }}.tar.bz2

  build-win:
    runs-on: windows-latest

    # According to
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2019
    # VS2019 is what is installed in the hosted runners:
    #   Version: VisualStudio/16.3.6+29418.71
    #   Location: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: .\racket\src\worksp
      shell: cmd
      run: |
        call msvcprep.bat x86_amd64
        call build.bat
        call ..\..\racket.exe csbuild.rkt -- --recurse-submodules --depth=1

  # Tests
  # Unfortunately Actions does not support atm yaml anchors
  # otherwise all the following jobs could be simplified
  # Note: the reason we cannot transform this into a matrix
  # build is because we cannot use variables in the needs keyword.
  test-cgc:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        cify: [cify, nocify]

    runs-on: ${{ matrix.os }}

    needs: build-racketcgc

    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: racketcgc-${{ matrix.os }}-${{ matrix.cify }}-x64_git${{ github.sha }}
          path: ${{ runner.temp }}
      - name: Untar
        working-directory: ${{ runner.temp }}
        run: tar -xvjf racketcgc-${{ matrix.os }}-${{ matrix.cify }}-x64_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        working-directory: ${{ runner.temp }}
        run: echo "::set-env name=PATH::$PWD/racketcgc/bin:$PATH"
      - name: Check for Racket
        run: racket --version
      - name: Install catalog
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Run tests/racket/test
        run: raco test -l tests/racket/test
      - name: Run tests/racket/contract/all
        run: racket -l tests/racket/contract/all
      - name: Run tests/json/json
        run: raco test -l tests/json/json
      - name: Run tests/file/main
        run: raco test -l tests/file/main
      - name: Run tests/net/head
        run: raco test -l tests/net/head
      - name: Run tests/net/uri-codec
        run: raco test -l tests/net/uri-codec
      - name: Run tests/net/url
        run: raco test -l tests/net/url
      - name: Run tests/net/url-port
        run: raco test -l tests/net/url-port
      - name: Run tests/net/encoders
        run: raco test -l tests/net/encoders
      - name: Run tests/openssl/basic
        run: raco test -l tests/openssl/basic
      - name: Run tests/openssl/https
        run: raco test -l tests/openssl/https
      - name: Run tests/match/main
        run: raco test -l tests/match/main
      - name: Run tests/zo-path
        run: raco test -l tests/zo-path
      - name: Run tests/xml
        run: raco test -c tests/xml
      - name: Run tests/future
        run: raco test -c tests/future
      - name: Run tests/stxparse
        run: raco test -c tests/stxparse
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Run db tests
        run: raco test -l tests/db/all-tests
      - name: Run syntax tests
        run: raco test -c tests/syntax

  test-3m:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        cify: [cify, nocify]
        jit: [jit, nojit]
        efp: [efp, noefp]
        exclude:
          - jit: nojit
            efp: efp

    runs-on: ${{ matrix.os }}

    needs: build-racket3m

    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: racket3m-${{ matrix.os }}-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}
          path: ${{ runner.temp }}
      - name: Untar
        working-directory: ${{ runner.temp }}
        run: tar -xvjf racket3m-${{ matrix.os }}-${{ matrix.cify }}-${{ matrix.jit }}-${{ matrix.efp }}-x64_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        working-directory: ${{ runner.temp }}
        run: echo "::set-env name=PATH::$PWD/racket3m/bin:$PATH"
      - name: Check for Racket
        run: racket --version
      - name: Install catalog and required packages
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Run tests/racket/test
        run: raco test -l tests/racket/test
      - name: Run tests/racket/contract/all
        run: racket -l tests/racket/contract/all
      - name: Run tests/json/json
        run: raco test -l tests/json/json
      - name: Run tests/file/main
        run: raco test -l tests/file/main
      - name: Run tests/net/head
        run: raco test -l tests/net/head
      - name: Run tests/net/uri-codec
        run: raco test -l tests/net/uri-codec
      - name: Run tests/net/url
        run: raco test -l tests/net/url
      - name: Run tests/net/url-port
        run: raco test -l tests/net/url-port
      - name: Run tests/net/encoders
        run: raco test -l tests/net/encoders
      - name: Run tests/openssl/basic
        run: raco test -l tests/openssl/basic
      - name: Run tests/openssl/https
        run: raco test -l tests/openssl/https
      - name: Run tests/match/main
        run: raco test -l tests/match/main
      - name: Run tests/zo-path
        run: raco test -l tests/zo-path
      - name: Run tests/xml
        run: raco test -c tests/xml
      - name: Run tests/future
        run: raco test -c tests/future
      - name: Run tests/stxparse
        run: raco test -c tests/stxparse
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Run db tests
        run: raco test -l tests/db/all-tests

  test-cs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]

    runs-on: ${{ matrix.os }}

    needs: build-racketcs

    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: racketcs-${{ matrix.os }}-x64_git${{ github.sha }}
          path: ${{ runner.temp }}
      - name: Untar
        working-directory: ${{ runner.temp }}
        run: tar -xvjf racketcs-${{ matrix.os }}-x64_git${{ github.sha }}.tar.bz2
      - name: Extend PATH with Racket executable
        working-directory: ${{ runner.temp }}
        run: echo "::set-env name=PATH::$PWD/racketcs/bin:$PATH"
      - name: Check for Racket
        run: racket --version
      - name: Install catalog and required packages
        run: |
          racket -l- pkg/dirs-catalog --immediate $PWD/rktcat $PWD/pkgs/
          raco pkg config --set catalogs $PWD/rktcat/ https://pkgs.racket-lang.org https://planet-compats.racket-lang.org
      - name: Install racket-test dependency
        run: raco pkg install --auto racket-test
      - name: Run tests/racket/test
        run: raco test -l tests/racket/test
      - name: Run tests/racket/contract/all
        run: racket -l tests/racket/contract/all
      - name: Run tests/json/json
        run: raco test -l tests/json/json
      - name: Run tests/file/main
        run: raco test -l tests/file/main
      - name: Run tests/net/head
        run: raco test -l tests/net/head
      - name: Run tests/net/uri-codec
        run: raco test -l tests/net/uri-codec
      - name: Run tests/net/url
        run: raco test -l tests/net/url
      - name: Run tests/net/url-port
        run: raco test -l tests/net/url-port
      - name: Run tests/net/encoders
        run: raco test -l tests/net/encoders
      - name: Run tests/openssl/basic
        run: raco test -l tests/openssl/basic
      - name: Run tests/openssl/https
        run: raco test -l tests/openssl/https
      - name: Run tests/match/main
        run: raco test -l tests/match/main
      - name: Run tests/zo-path
        run: raco test -l tests/zo-path
      - name: Run tests/xml
        run: raco test -c tests/xml
      - name: Run tests/future
        run: raco test -c tests/future
      - name: Run tests/stxparse
        run: raco test -c tests/stxparse
      - name: Install db tests dependency
        run: raco pkg install --auto db-test
      - name: Run db tests
        run: raco test -l tests/db/all-tests
